"""Добавлено поле profile_picture в модель User

Revision ID: 30dcf5d6ad7d
Revises: 9976053d4c1e
Create Date: 2025-05-04 19:33:53.151019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dcf5d6ad7d'
down_revision = '9976053d4c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
