"""Добавлено поле profile_picture в модель User

Revision ID: 790eab14a16f
Revises: 30dcf5d6ad7d
Create Date: 2025-05-04 19:56:24.923015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790eab14a16f'
down_revision = '30dcf5d6ad7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
